import type { FileType, NormalizedField } from "@/lib/equity-close/types";

export const FILE_TYPES: FileType[] = [
  "Grant Activity",
  "Expense Report",
  "Org Mapping",
  "Manual Tracker",
];

export const NORMALIZED_FIELDS: NormalizedField[] = [
  {
    key: "employee_name",
    label: "Employee Name",
    description: "Full employee name as it appears in source records.",
    requiredFor: ["Grant Activity", "Expense Report"],
    suggestedFor: ["Manual Tracker"],
    category: "core",
    synonyms: ["employee", "employee name", "name", "participant", "holder name"],
  },
  {
    key: "employee_id",
    label: "Employee ID",
    description: "Internal employee identifier.",
    requiredFor: [],
    suggestedFor: ["Grant Activity", "Expense Report", "Org Mapping", "Manual Tracker"],
    category: "core",
    synonyms: ["employee id", "emplid", "worker id", "user id", "person id"],
  },
  {
    key: "grant_number",
    label: "Grant Number",
    description: "Unique award or grant identifier.",
    requiredFor: ["Grant Activity"],
    suggestedFor: ["Expense Report", "Manual Tracker"],
    category: "core",
    synonyms: ["grant", "grant number", "award id", "award number", "grant id"],
  },
  {
    key: "award_type",
    label: "Award Type",
    description: "Award classification such as RSU, PSU, option, ESPP.",
    requiredFor: [],
    suggestedFor: ["Grant Activity", "Expense Report", "Manual Tracker"],
    category: "core",
    synonyms: ["award type", "type", "grant type", "equity type"],
  },
  {
    key: "grant_date",
    label: "Grant Date",
    description: "Date the award was granted.",
    requiredFor: [],
    suggestedFor: ["Grant Activity", "Manual Tracker"],
    category: "dates",
    synonyms: ["grant date", "award date", "issued date"],
  },
  {
    key: "vesting_date",
    label: "Vesting Date",
    description: "Scheduled vesting date or vest tranche date.",
    requiredFor: [],
    suggestedFor: ["Grant Activity", "Manual Tracker"],
    category: "dates",
    synonyms: ["vesting date", "vest date", "release date"],
  },
  {
    key: "expense_start_date",
    label: "Expense Start Date",
    description: "Date expense recognition starts.",
    requiredFor: [],
    suggestedFor: ["Expense Report", "Manual Tracker"],
    category: "dates",
    synonyms: ["expense start date", "service start date", "start date"],
  },
  {
    key: "service_period_end",
    label: "Service Period End",
    description: "Service or amortization end date.",
    requiredFor: [],
    suggestedFor: ["Expense Report", "Manual Tracker"],
    category: "dates",
    synonyms: ["service period end", "service end date", "end date"],
  },
  {
    key: "shares_granted",
    label: "Shares Granted",
    description: "Original granted quantity.",
    requiredFor: [],
    suggestedFor: ["Grant Activity", "Manual Tracker"],
    category: "amounts",
    synonyms: ["shares granted", "granted shares", "quantity", "shares"],
  },
  {
    key: "fair_value_per_share",
    label: "Fair Value Per Share",
    description: "Fair value used for expense recognition.",
    requiredFor: [],
    suggestedFor: ["Grant Activity", "Expense Report", "Manual Tracker"],
    category: "amounts",
    synonyms: ["fair value", "fv", "fair value per share", "grant date fair value"],
  },
  {
    key: "current_period_expense",
    label: "Current Period Expense",
    description: "Expense recognized in the current period.",
    requiredFor: ["Expense Report"],
    suggestedFor: ["Manual Tracker"],
    category: "amounts",
    synonyms: ["expense", "current expense", "period expense", "current period expense"],
  },
  {
    key: "cumulative_expense",
    label: "Cumulative Expense",
    description: "Expense recognized to date.",
    requiredFor: [],
    suggestedFor: ["Expense Report", "Manual Tracker"],
    category: "amounts",
    synonyms: ["cumulative expense", "ytd expense", "ltd expense", "total expense"],
  },
  {
    key: "legal_entity",
    label: "Legal Entity",
    description: "Employing or grant-holding legal entity.",
    requiredFor: [],
    suggestedFor: ["Grant Activity", "Expense Report", "Org Mapping", "Manual Tracker"],
    category: "dimensions",
    synonyms: ["entity", "legal entity", "company", "employing entity"],
  },
  {
    key: "department",
    label: "Department",
    description: "Department or function.",
    requiredFor: [],
    suggestedFor: ["Expense Report", "Org Mapping", "Manual Tracker"],
    category: "dimensions",
    synonyms: ["department", "dept", "function"],
  },
  {
    key: "cost_center",
    label: "Cost Center",
    description: "Cost center associated with the expense or employee.",
    requiredFor: [],
    suggestedFor: ["Expense Report", "Org Mapping", "Manual Tracker"],
    category: "dimensions",
    synonyms: ["cost center", "costcentre", "cc"],
  },
  {
    key: "country",
    label: "Country",
    description: "Employee or entity country.",
    requiredFor: [],
    suggestedFor: ["Expense Report", "Org Mapping", "Manual Tracker"],
    category: "dimensions",
    synonyms: ["country", "location country", "employee country"],
  },
  {
    key: "performance_status",
    label: "Performance Status",
    description: "Performance achievement or PSU status.",
    requiredFor: [],
    suggestedFor: ["Manual Tracker", "Grant Activity"],
    category: "performance",
    synonyms: ["performance", "performance status", "achievement", "psu status"],
  },
  {
    key: "performance_status_date",
    label: "Performance Status Date",
    description: "Date performance status was determined.",
    requiredFor: [],
    suggestedFor: ["Manual Tracker", "Grant Activity"],
    category: "performance",
    synonyms: ["performance status date", "measurement date", "status date"],
  },
];

export const STORAGE_KEY = "equity-close-os:mapping-templates:v1";

export const FILE_TYPE_REQUIRED_FIELDS: Record<FileType, string[]> = {
  "Grant Activity": ["employee_name", "grant_number"],
  "Expense Report": ["employee_name", "current_period_expense"],
  "Org Mapping": [],
  "Manual Tracker": [],
};
